var my_arrayFurniture = [

" http://www.made.com/new-in  ",
" http://www.worldstores.co.uk/ ",
" http://www.chilternoakfurniture.co.uk/?gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXX2BnytNMjikiYNc9Klw3sd_tlH2TgxSPrCeemvsCUYaAiCG8P8HAQ ",
" http://www.habitat.co.uk/ ",
" http://www.maisonsdumonde.com/UK/en ",
" http://www.lovethesign.com/uk/  ",
" http://www.furniturevillage.co.uk/  ",
" https://www.barkerandstonehouse.co.uk/new-in/ ",
" http://furniture123.co.uk/  ",
" http://jysk.co.uk/  ",
" http://www.debenhams.com/furniture?cmp=KNC_3965920030_152000709_8915693469_%2Bfurniture_b&label=jan15generic2&offfor170815&cmp=KNC_3965920030_152000709_8915693469_%2Bfurniture_b&mkwid=sfrKrOuAq|pcrid|161871675495|pkw|%2Bfurniture|pmt|b|pdv|c|prd|&mdrt=furniture&gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXTosJM02VFz_3cX5bI2w5xIIGolqSIyhAH0iqvmAVzkaApnS8P8HAQ  ",
" https://www.styleourhome.com/?gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXT1gqpqnAR7pgTJ3P5s6iX9Ocb8QNQwj1Tv0FQ3-k3waAg6R8P8HAQ  ",
" http://www.johnlewis.com/home-garden/all-furniture/c60000741?rdr=1&s_kwcid=1dx43700013407501671&tmad=c&tmcampid=1&gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXbzeFkuIUjpwSC_F48DS-ywiF05t-mIr3zV3FSD5VvUaAv1q8P8HAQ&gclsrc=aw.ds ",
" https://www.swooneditions.com/new ",
" http://www.oakfurnitureland.co.uk/?ec=3396737029&gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXewPEA7hrAUUlzsqEf3juXdwQEiz3iteRVjrOTkEeMoaAgZt8P8HAQ#aff757c6f26868e ",
" http://www.homebase.co.uk/en/homebaseuk/furniture ",
" http://www.ikea.com/gb/en/  ",
" https://dwell.co.uk/  ",
" http://www.roseandgrey.co.uk/ ",
" http://www.argos.co.uk/static/Browse/ID72/33005908/c_1/1%7Ccategory_root%7CHome+and+garden%7C33005908.htm ",
" https://funique.co.uk/  ",
" https://www.thefurnshop.co.uk/#b  ",
" http://www.turquoise.co.uk/ ",
" https://www.sabichi.co.uk/furniture.html  ",
" https://www.conranshop.co.uk/new-arrivals.html?___SID=U ",
" http://furnish.co.uk/ ",
" http://modusfurniture.co.uk/  ",
" https://www.zurleys.co.uk/  ",
" http://www.furnitureplusonline.co.uk/ ",
" http://idea-forhome.co.uk/  ",
" https://www.choicefurnituresuperstore.co.uk/  ",
" http://www.con-tempofurniture.co.uk/ranges/quercus-oak-furniture?gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXXlcxKh5d2cuXaAtZG7qkg-zrVT_8_ESJNv0lH1GgUUaAsH48P8HAQ ",
" https://www.onlinefurnitureworld.co.uk/ ",
" http://www.fads.co.uk/  ",
" https://furnituredirectuk.net/  ",
" http://www.jsfurniture.co.uk/ ",
" https://www.houseology.com/new  ",
" https://www.franceshunt.co.uk/  ",
" http://www.roselandfurniture.com/ ",
" https://www.bluesuntree.co.uk/site/products/new-items ",
" https://www.ncffurnishings.co.uk/ ",
" http://www.milandirect.co.uk/home-furniture/new-arrivals  ",
" http://www.dfs.co.uk/ ",
" http://www.furnitureland.co.uk/ ",
" https://www.sterlingfurniture.co.uk/  ",
" http://www.thefurnituremarket.co.uk/oakfurniture.asp  ",
" http://www.fusionliving.co.uk/  ",
" https://www.my-furniture.com/ ",
" http://www.worldstores.co.uk/c/Furniture.htm?affiliate=WS-google-search&gclid=Cj0KEQiAguXBBRCE_pbQ5reuq8MBEiQANji2LYGJOeVOxICFSzU2Q3M9N5_Csp4qJqM5g2nnJlg4wXEaAgtq8P8HAQ  ",
" https://www.chicfurnitureandgift.co.uk/ ",
" http://www.cousinsfurniture.co.uk/  ",
" https://www.brighthouse.co.uk/home-furniture?gclid=Cj0KEQiAguXBBRCE_pbQ5reuq8MBEiQANji2LRV7JMRR1JouttiZxg0WvS7WIdWPjuObigW4kOCg-cwaAmif8P8HAQ ",
" http://www.leberta.co.uk/?gclid=Cj0KEQiAguXBBRCE_pbQ5reuq8MBEiQANji2LZv8b2YLEhEk1-Yvpq1Sq0PFSmntLYzvRPv7wKrXepkaAh2o8P8HAQ  ",
" https://www.arthauss.co.uk/ ",
" http://www.harveysfurniture.co.uk/  ",
" http://www.furniturechoice.co.uk/ ",
" http://www.homearena.co.uk/ ",
" http://www.grahamandgreen.co.uk/  ",
" http://www.tesco.com/direct/home-furniture/ ",
" http://www.mrgregor.co.uk/  "

];
var riFurniture = Math.floor(Math.random() * my_arrayFurniture.length);
var fileFurniture = my_arrayFurniture[riFurniture];