var my_arrayGifts = [

" https://www.buyagift.co.uk/ ",
" http://www.prezzybox.com/ ",
" https://www.gettingpersonal.co.uk/  ",
" https://www.thegreatgiftcompany.co.uk/  ",
" http://www.temptationgifts.com/ ",
" http://www.thewhitecompany.com/c/gifts  ",
" http://www.findmeagift.co.uk/ ",
" http://www.smartgiftsolutions.co.uk/gifts-by-occasions  ",
" http://www.flowers24hours.co.uk/gifts/  ",
" https://www.photobox.co.uk/shop?channel=10268&ectrans=1&gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXc73F8qIlMUO5aL14o0eC0NBVlKNtUOk8acfbtoAA_EaAjU38P8HAQ  ",
" https://www.thegiftexperience.co.uk/occasions/index.html  ",
" https://www.moonpig.com/uk/gift/gift-boxes/ ",
" http://www.gifts.co.uk/ ",
" http://giftsonlineuk.net/#  ",
" https://www.firebox.com/whatsnew?&page=1  ",
" http://www.johnlewis.com/browse/gifts/british-themed-gifts/_/N-amt  ",
" http://www.iwantoneofthose.com/gifts.list ",
" http://www.notonthehighstreet.com/  ",
" http://www.english-heritageshop.org.uk/ ",
" https://www.dotcomgiftshop.com/just-arrived?ll=menutopnav ",
" http://www.marksandspencer.com/c/flowers-and-gifts?extid=ps_ggl_UK_Gen_Homeware_GiftsGiftShop_OnlineGifts&kwid=1032770496_Google+Adwords&s_kwcid=AL!2750!3!57079219433!e!!g!!gifts%20online%20uk&device=c&ef_id=Vwld0QAABHDgF8gI:20161125205350:s ",
" http://reve-en-vert.com/product-category/new-arrivals/  ",
" https://www.hampergifts.co.uk/newgifts.cfm  ",
" http://www.menkind.co.uk/new  ",
" http://www.harrods.com/boutiques/the-gift-guide ",
" http://www.theoriginalgift.co.uk/ ",
" http://www.lightinthebox.com/c/gifts_4975 ",
" http://www.royalcollectionshop.co.uk/gifts.html/  ",
" https://shop.nationaltrust.org.uk/gifts/c168  ",
" http://www.moltonbrown.co.uk/store/new/cat260016/ ",
" https://www.cadburygiftsdirect.co.uk/ ",
" https://www.newbyteas.co.uk/  ",
" https://www.ijustloveit.co.uk/  ",
" http://www.oddbins.com/gifts  ",
" https://art.nationalgalleries.org/shop/discover/limited-editions?gclid=Cj0KEQiA39_BBRD0w-_rmOrc__8BEiQA-ETxXduXpbgoPx4TtB3LM20cfhKWeWGenc-xcVUF3xaHtWAaApK_8P8HAQ ",
" https://www.sciencemuseumshop.co.uk/  ",
" http://www.thegiftcardcentre.co.uk/ ",
" http://www.debenhams.com/gifts  ",
" http://shop.tate.org.uk/  ",
" https://www.funkypigeon.com/Gifts.aspx?type=iframeSG  ",
" http://www.traidcraftshop.co.uk/  ",
" http://www.red5.co.uk/  ",
" https://www.thepresentfinder.co.uk/dept/new-gift-ideas_d01109.htm ",
" http://www.hotelchocolat.com/uk/  ",
" http://www.instant-gifts.co.uk/ ",
" https://www.fortnumandmason.com/  ",
" https://www.buyagift.co.uk/?Channel=PPC&cm_mmc=google-_-GEN+-+Gifts+Generic+-+Exact-_-Gifts+Generic+Online-_-gifts%20online%20uk&mkwid=sIm9okpfY_dc&pcrid=74001015976&pkw=gifts%20online%20uk&pmt=e&DD=Generics&gclid=Cj0KEQiAguXBBRCE_pbQ5reuq8MBEiQANji2Ldc2E69lcH1L5aiaHvwdsW8HjuvRJN_mxBIUTd9ImY4aAo2l8P8HAQ  ",
" https://www.one4allgiftcard.co.uk/  ",
" https://www.cardfactory.co.uk/  ",
" https://www.ijustloveit.co.uk/  ",
" http://www.engravedgiftsonline.co.uk/ ",
" https://amnestyshop.org.uk/ ",
" http://www.musicalgiftsonline.co.uk/  ",
" http://www.allthingsgifts.co.uk/  ",
" https://www.biscuiteers.com/  ",
" http://www.engraving-excellence.co.uk/  ",
" http://www.crabtree-evelyn.co.uk/home.html  ",
" http://www.campusgifts.co.uk/ ",
" http://www.flutterbyes.co.uk/ ",
" http://www.luckies.co.uk/ "

];
var riGifts = Math.floor(Math.random() * my_arrayGifts.length); 
document.getElementById("IntroAnimation").src = my_arrayGifts[riGifts];
document.getElementById("IntroAnimation").src = fileGifts;
var fileGifts = my_arrayGifts[riGifts];